### ISSUE TITLE
`every_x_percent` should be made consistent with `every_n_records`?

### ISSUE THREAD

**Issue by movermeyer** [exactEarth/ProgressTracker#10]
When I wrote this, I felt that `every_x_percent` sounded better than `every_n_percent` (which is similar to `every_n_records`), and then played some mental acrobatics to justify it: 

> "x is different than n to differentiate percentages from absolute numbers".

I periodically question this decision, as it might be considered to be harder for users to remember ("Is this one the x, or the other one?").

What are your thoughts?

**Comment by movermeyer** [comment]
@NickG123

**Comment by NickG123** [comment]
🤷‍♂️ I don't really care either way

**Comment by movermeyer** [comment]
Ok.
This first few issues are really just code review of the existing code.
