### ISSUE TITLE
Remove exception raised when processing unbounded iterables with `every_x_percent`

### ISSUE THREAD

**Issue by movermeyer** [exactEarth/ProgressTracker#11]
Right now, [the code raises an `Exception`](https://github.com/movermeyer/ProgressTracker/blob/12e2f7482dffc21c3752c84fa6348da8eec0163f/progress_tracker/progress_tracker.py#L62) whenever an unbounded iterable is provided with the `every_x_percent` parameter set.

I believe that we should remove this check, and simply ignore the `every_x_percent` parameter in this case.

If users are processing an iterable, and they don't know whether it is bounded or not, it would be nice if they could set the parameters once. I never want the user to have to write code like this:

```python
for generator in generators:
    if iterable_has_length(generator):
         for item in track_progress(generator, every_n_records=100, every_x_percent=10):
             process(item)
    else:
         for item in track_progress(generator, every_n_records=100):
             process(item)
```

or equivalent:

```python
for generator in generators:
    params = {"every_n_records": 100}
    if iterable_has_length(generator):
        params["every_x_percent"] = 10
    for item in track_progress(generator, **params):
             process(item)
```

They should not have to mimic the check we do inside of `ProgressTracker` in their code. 
`track_progress` will simply report with the information they want when possible.

**Comment by NickG123** [comment]
I'm not so sure about that one.  I think it would be a bigger shame if a user put something like `track_progress(generator, every_x_percent=10)` and never got any output.

**Comment by movermeyer** [comment]
>  I think it would be a bigger shame if a user put something like track_progress(generator, every_x_percent=10) and never got any output.

I would counter by saying that is an obvious problem to notice when testing, as opposed to the other, which is less likely to be caught (since people frequently only sunny-day test).

I guess I generally think of this as just a logging library, so not logging when it can't give a better answer is a fine failure mode.

I don't like the code that the "raise Exception" case produces in client software.

**Comment by movermeyer** [comment]
What sort of problems are you imagining?
