### ISSUE TITLE
Remove `idle_timeout`

### ISSUE THREAD

**Issue by movermeyer** [exactEarth/ProgressTracker#4]
`every_n_seconds_idle` was originally supposed to give you a printout if there hadn't been a printout in a while *and* the process hadn't received a message in a while.

For example, imagine that you are processing an infinite message stream that arrives in bursts. You have `track_progress` printing out every 100 messages (with `every_n_records=100`), but it processed only 95 before it had to wait for more messages. You might want it to print out a message saying "I processed 95 messages, but haven't seen a new one in several minutes" while it is waiting, instead of it not telling you anything until 5 more messages come in.

The way `ProgressTracker.__iter__()` is structured, it cannot do any computation until the underlying iterable provides it with a new message.

Right now, it'll print out when the 96th message arrives, which could still be considered useful ("Sorry I was so quiet for so long, but I was waiting on a new message"), but is a different kind of message.

Implement this functionality, or remove it?

**Comment by movermeyer** [comment]
`every_n_seconds` has a similar problem.

**Comment by NickG123** [comment]
I don't think that can be done without a separate thread, which seems like overkill to me

**Comment by NickG123** [comment]
The idea is not "Output exactly every n seconds" its "if n seconds have gone by, then output when next possible"

**Comment by movermeyer** [comment]
> I don't think that can be done without a separate thread, which seems like overkill to me

I agree.

Using the `track_progress()` method, I don't think that `every_n_seconds_idle` makes sense.

Before, when you were calling `should_report` directly and only calling `check` after each item was processed, it made might have made sense.

**Comment by NickG123** [comment]
I'm not convinced that this it warrants removing.  Lets make a timeline:

| Time Offset | Iterations |
|-------------|------------|
| 0           | 300        |
| 1           | 100        |
| 2           | 0          |
| 3           | 0          |
| 4           | 1          | 
| 5           | 0          |
| 6           | 0          |

The `every_n_seconds_idle` parameter is perfect for identifying a small chunk of data on its own.

So for example, if I were to use something like `every_n_records=100, every_n_seconds_idle=60` then I would get 3 printouts for T+0, 1 for T+1, and then one for T+4.  Without `every_n_seconds_idle`, I wouldn't get a printout then.

You might argue that I could use `every_n_seconds` for this task, but then I would end up with more 4 printouts for T+0 and 2 for T+1

**Comment by movermeyer** [comment]
You are correct. Sorry for wasting your time.
