### ISSUE TITLE
Add a timeout for "n seconds since last trigger"

### ISSUE THREAD

**Issue by movermeyer** [exactEarth/ProgressTracker#7]
`every_n_seconds` only cares about how long it has been since `every_n_seconds` last triggered.

I question its value. I think a more useful version would be something that triggered if it had been more than `n` seconds since **any condition** triggered.

Something like:

| Parameter                           | Trigger condition                                             |
| ----------------------------------- | ------------------------------------------------------------- |
| `every_n_seconds`                   | It's been > n seconds since last trigger of `every_n_seconds` |
| `every_n_seconds_idle`              | It's been > n seconds since last record processed             |
| `every_n_seconds_since_last_report` | It's been > n seconds since last trigger of anything          |

At that point, I'm not sure I'd ever use `every_n_seconds`.

**Comment by NickG123** [comment]
Hmm, I thought this was the behaviour of `every_n_seconds_idle`.  Guess I misunderstood 😕 
I agree that would be helpful

**Comment by movermeyer** [comment]
> I thought this was the behaviour of every_n_seconds_idle

Hence my confusion earlier. Keeping them all straight without docs was tough. I'm writing docs now.

**Comment by movermeyer** [comment]
What is the point of each?

* `every_n_seconds` is meant to ensure that if records are being processed, you get a report roughly every n seconds. 
    * It's downside is that it reports regardless of whether there has been a report recently, which is louder than necessary. Remove this in favour of `every_n_seconds_since_last_report`?

* `every_n_seconds_idle` is meant to let you know when the stream has been quiet for a while, and processing is continuing again. 
    * It's downside is in the way it is currently implemented. Currently, if a record takes longer than n seconds to process, it is thought of as "idle" and triggers a report. Fix this so that it reports `every_n_seconds_idle` before yielding the next item, and resets the `idle_timeout` after the yield?
        * A nice side-effect of this is that you can then measure the processing time and offer to report if processing of a record exceeds a given threshold. IDK how useful that would be.
